-- 기존 테이블이 있다면 삭제
DROP TABLE BOARD CASCADE CONSTRAINTS PURGE;
DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;

-- MEMBER 테이블 생성
CREATE TABLE MEMBER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- BOARD 테이블 생성
CREATE TABLE BOARD (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    AUTHOR VARCHAR2(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- BOARD_COMMENT 테이블 생성
CREATE TABLE BOARD_COMMENT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BOARD_ID NUMBER NOT NULL,
    CONTENT VARCHAR2(1000) NOT NULL,
    AUTHOR VARCHAR2(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BOARD_ID) REFERENCES BOARD(ID) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX IDX_MEMBER_EMAIL ON MEMBER(EMAIL);
CREATE INDEX IDX_BOARD_AUTHOR ON BOARD(AUTHOR);
CREATE INDEX IDX_BOARD_CREATED_DATE ON BOARD(CREATED_DATE);
CREATE INDEX IDX_COMMENT_BOARD_ID ON BOARD_COMMENT(BOARD_ID); 